### ISSUE TITLE
Link to Heroku and instructions for the app

### ISSUE THREAD

**Issue by veredrec** [FACN3/Auto-Completer#29]
It would be great if you can add the link to your app on Heroku to your README.
It is nice to have the instructions on how to clone the app on your README as well :smile:

**Comment by SamiSha99** [comment]
@veredrec Done that.

**Comment by veredrec** [comment]
@SamiSha99 Great! One small thing to change - you wrote that the user should run `devStart` but your script is actually `devstart` so just fix this small thing as it would be perfect :wink:

**Comment by SamiSha99** [comment]
Fixed :smile:

**Comment by veredrec** [comment]
Perfect!
