### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by veredrec** [FACN3/Auto-Completer#30]
From what I see, it seems like the autocomplete function does not work. When I type a letter or two, I don't see any results on the page

**Comment by sophieeejw** [comment]
it works locally when cloned and run... must be something wrong with deploying it on heroku??

**Comment by SamiSha99** [comment]
Like @sophieeejw said, the app seems to work fine if launched locally, I think the heroku app broke it, we tried to fix that but we couldn't figure it out.

**Comment by NickP123** [comment]
This is resolved - please try via the heroku link. We will add this to the top of the readme. Thanks

**Comment by veredrec** [comment]
It looks great! :100:
