### ISSUE TITLE
README is great! 

### ISSUE THREAD

**Issue by veredrec** [FACN3/Auto-Completer#31]
I LOVE your README. It is detailed, clear and informative! 
Good job! :tada:

**Comment by SamiSha99** [comment]
And that's an issue too.

/sarcasm

**Comment by veredrec** [comment]
Since you closed it while we are still code reviewing - I'm reopening the issue, so the team members have a chance to read the issue.

**Comment by veredrec** [comment]
And @SamiSha99 this was an honest issue and comment, not sarcastic at all. I meant what I wrote.

**Comment by SamiSha99** [comment]
No I meant my comment as being sarcastic :P not yours.

**Comment by veredrec** [comment]
No problem :smile:

**Comment by NickP123** [comment]
Thanks Vered, appreciated.  I'll close the issue at this point
