### ISSUE TITLE
logs in router.js

### ISSUE THREAD

**Issue by shiryz** [FACN3/Auto-Completer#37]
remove any unnecessary console logs... 
*https://github.com/FACN3/Auto-Completer/blob/master/src/router.js#L12*

**Comment by SamiSha99** [comment]
Should we remove all console logs? just to be clear.

**Comment by shiryz** [comment]
@SamiSha99 if you need that log for some reason then you can keep it, for example the log of the port in the terminal, 99% of the cases you don't need it

**Comment by SamiSha99** [comment]
Alright, thanks for the advice!

**Comment by shiryz** [comment]
@SamiSha99 you shouldn't self close an issue but tag me to close

**Comment by SamiSha99** [comment]
@shiryz Sorry :c
